# Generated by Django 2.2.3 on 2020-04-06 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(auto_now_add=True)),
                ('consumption', models.PositiveIntegerField()),
                ('measurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurers.Measurer')),
            ],
        ),
    ]
