# Generated by Django 2.2.3 on 2020-04-08 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code', models.CharField(max_length=20)),
                ('house_id', models.CharField(max_length=20, unique=True)),
                ('measurer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='measurers.Measurer')),
            ],
        ),
    ]
