# Generated by Django 2.2.3 on 2020-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurer',
            name='measure',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
